db_host: ""          # will be set dynamically from Terraform output
frontend_ip: ""      # will be set dynamically from Terraform output
db_user: admin
db_password: admin
aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
repo_url: "https://github.com/zhashmik/user-management-backend.git"
repo_branch: "security"
app_dir: "/home/ubuntu/user-management-backend"
